import * as stylex from '@stylexjs/stylex'
import { d, g, t } from '@/app/tokens.stylex'

const riseKf = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(16px)' },
})

export const chrome = stylex.create({
  place: {
    position: 'relative',
    minHeight: '100svh',
    display: 'flex',
    flexDirection: 'column',
    paddingTop: { default: '104px', '@media (max-width: 880px)': '96px' },
    paddingInline: { default: '30px', '@media (max-width: 880px)': '18px' },
    paddingBottom: { default: '72px', '@media (max-width: 880px)': '56px' },
  },
  pintro: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    marginBlock: 'auto',
  },
  rise: {
    animationName: riseKf,
    animationDuration: '0.9s',
    animationTimingFunction: 'cubic-bezier(0.2, 0.7, 0.2, 1)',
    animationFillMode: 'both',
  },
  eyebrow: {
    fontFamily: t.mono,
    fontSize: '12px',
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    textWrap: 'balance',
    color: t.mut,
  },
  h1: {
    fontSize: 'clamp(34px, 5vw, 48px)',
    lineHeight: 1.02,
    letterSpacing: '-0.035em',
    fontWeight: 550,
    marginTop: '18px',
    marginBottom: '18px',
    marginInline: 'auto',
    maxWidth: '13ch',
  },
  lede: {
    fontSize: '16px',
    lineHeight: 1.65,
    color: t.mut,
    maxWidth: '32em',
    marginTop: 0,
    marginBottom: '36px',
    marginInline: 'auto',
    textShadow: `0 1px 8px color-mix(in srgb, ${t.void} 80%, transparent)`,
  },
  btn: {
    display: 'inline-block',
    fontFamily: t.sans,
    fontSize: '15px',
    lineHeight: '20px',
    fontWeight: 560,
    borderRadius: '10px',
    paddingBlock: '12px',
    paddingInline: '22px',
    cursor: 'pointer',
    transitionProperty: 'background-color, color',
    transitionDuration: '0.18s',
    transitionTimingFunction: 'ease',
  },
  cta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '9px',
  },
  gamePrimary: {
    fontSize: '16px',
    fontWeight: 750,
    letterSpacing: '-0.01em',
    paddingBlock: '13px',
    paddingInline: '24px',
    borderWidth: '2.5px',
    borderStyle: 'solid',
    borderColor: g.gline,
    borderRadius: '14px',
    backgroundColor: d.gc,
    boxShadow: {
      default: `0 4px 0 ${g.grim}`,
      ':active:enabled': `0 1px 0 ${g.grim}`,
      ':disabled': `0 2px 0 ${g.grim}`,
    },
    color: g.gon,
    transitionProperty: 'transform, box-shadow, filter, opacity',
    transitionDuration: '0.12s, 0.12s, 0.15s, 0.15s',
    transitionTimingFunction: 'ease',
    filter: { default: null, ':hover:enabled': 'brightness(1.06)' },
    transform: { default: null, ':active:enabled': 'translateY(3px)' },
    opacity: { default: null, ':disabled': 0.4 },
    cursor: { default: 'pointer', ':disabled': 'default' },
  },
  ghost: {
    color: { default: t.mut, ':hover': t.ink },
    backgroundColor: {
      default: `color-mix(in srgb, ${t.void} 40%, transparent)`,
      ':hover': `color-mix(in srgb, ${t.void} 60%, transparent)`,
    },
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: `color-mix(in srgb, ${t.ink} 22%, transparent)`,
    borderRadius: '12px',
    boxShadow: {
      default: `0 3px 0 color-mix(in srgb, ${t.ink} 8%, transparent)`,
      ':active': `0 1px 0 color-mix(in srgb, ${t.ink} 8%, transparent)`,
    },
    transform: { default: null, ':active': 'translateY(2px)' },
    transitionProperty: 'transform, box-shadow, color, background-color',
    transitionDuration: '0.12s, 0.12s, 0.18s, 0.18s',
    transitionTimingFunction: 'ease',
  },
  kbdhint: {
    display: 'inline-grid',
    placeItems: 'center',
    minWidth: '21px',
    height: '21px',
    paddingBlock: 0,
    paddingInline: '5px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: `color-mix(in srgb, ${t.ink} 22%, transparent)`,
    borderRadius: '5px',
    backgroundColor: `color-mix(in srgb, ${t.ink} 6%, transparent)`,
    fontFamily: t.mono,
    fontSize: '12.5px',
    lineHeight: 1,
  },
  kbdOnGame: {
    borderColor: 'color-mix(in srgb, currentColor 45%, transparent)',
    backgroundColor: 'color-mix(in srgb, currentColor 14%, transparent)',
  },
  pcard: {
    position: 'relative',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: `color-mix(in srgb, ${t.ink} 24%, transparent)`,
    borderRadius: '18px',
    padding: '22px',
    backgroundColor: `color-mix(in srgb, ${t.ink} 3%, transparent)`,
    boxShadow: `0 5px 0 color-mix(in srgb, ${t.ink} 8%, transparent)`,
    animationName: riseKf,
    animationDuration: '0.5s',
    animationTimingFunction: 'cubic-bezier(0.2, 0.7, 0.2, 1)',
    animationFillMode: 'both',
  },
  pq: {
    fontSize: '19px',
    lineHeight: 1.55,
    letterSpacing: '-0.01em',
  },
  pill: {
    fontFamily: t.mono,
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: t.mut,
    backgroundColor: `color-mix(in srgb, ${t.ink} 4%, ${t.void})`,
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: `color-mix(in srgb, ${t.ink} 24%, transparent)`,
    borderRadius: '10px',
    paddingBlock: '5px',
    paddingInline: '10px',
    boxShadow: {
      default: `0 3px 0 color-mix(in srgb, ${t.ink} 12%, transparent)`,
      ':active': `0 1px 0 color-mix(in srgb, ${t.ink} 12%, transparent)`,
    },
    cursor: 'pointer',
    transitionProperty: 'transform, box-shadow, color, border-color',
    transitionDuration: '0.12s, 0.12s, 0.18s, 0.18s',
    transitionTimingFunction: 'ease',
    transform: { default: null, ':active': 'translateY(2px)' },
  },
  pillOn: {
    color: t.ink,
    borderColor: `color-mix(in srgb, ${t.ink} 55%, transparent)`,
  },
  voiced: {
    display: 'none',
  },
})
